server:
  port: 8080

spring:
  application:
    name: cep-lookup-api

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always