server:
  port: 8080

spring:
  application:
    name: cep-lookup-api
  cache:
    type: caffeine

caffeine:
  spec: maximumSize=500,expireAfterWrite=10m

via-cep:
  base-url: https://viacep.com.br

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
